name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest

    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Publish JS filename
        id: publish
        run: |
          filename=$(find dist/assets/*.js -type f -exec basename {} \;)
          echo "script-file=$filename" >> $GITHUB_OUTPUT

      - name: store artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: see what is in dist-files
        run: ls -la dist
      - name: output filename
        run: echo "output from build job is ${{ needs.build.outputs.script-file }}"
